### ISSUE TITLE
Design: Todo 폐이지 디자인 및 UI 마크업

### ISSUE THREAD

**Issue by yunkooo** [yunkooo/wanted-pre-onboarding-frontend#13]
## 작업내용
- [x] Todo 페이지 디자인
- [x] Todo 페이지 마크업
- [x] 부품 component 생성
